GET http://localhost:5199/games

####
POST http://localhost:5199/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "adventure",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}