GET http://localhost:5145/games/

####
POST http://localhost:5145/games
Content-Type: application/json

{
    "name": "uncharted",
    "genreId":3 ,
    "price": 10.00,
    "releaseDate": "2008-10-11"
}

#####

PUT http://localhost:5145/games/2
Content-Type: application/json

{
    "name": "zelda",
    "genreId": 3,
    "price": 9.99,
    "releaseDate": "2002-10-11"    
}

#####

DELETE http://localhost:5145/games/1